### PR TITLE
Add 3d bifurcation

### PR DESCRIPTION
**Pull request by bergbauer**
I added the basic functionality to create a 3D bifurcation.

The next step is to think about the mapping. What we currently use in our other code is the `skeleton` vector, in which the corner nodes of the square cylinder are stored.

### CODE REVIEW

**Comment by bergbauer** [comment]
t_pipe_3d

**Comment by marcfehling** [comment]
Thank you for the contribution! Sorry that I left this PR untouched for so long.
I'll go on and merge this as is. We could review the code and make further adjustments and generalizations in succeeding PRs. There are variables named after your original lung application example. Also, the clang-format file does not match the deal.II library, etc.

**Comment by marcfehling** [comment]
> The next step is to think about the mapping. What we currently use in our other code is the `skeleton` vector, in which the corner nodes of the square cylinder are stored.

Would it make sense to use a `MappingManifold` object for mapping once we have a proper manifold description (via `CylindricalManifold` [or a custom one that represents a cone] and `TransfiniteInterpolationManifold`)?

**Comment by marcfehling** [comment]
I'm still trying to understand the specifics of `create_cylinder` and `process_pipe`. Could you please extend the documentation?

I've been looking for example at the parameter `left_right_mixed_up_bottom` and can't figure out what that means...

Maybe we could simply things on the way, too.

**Pull request merged**
